### ISSUE TITLE
Upload broken

### ISSUE THREAD

**Issue by jonquixote** [chybie/file-upload-vue#4]
The demo doesn't seem to be working. https://vue-file-upload-1126b.firebaseapp.com
I have tried using the components in my own app and they do not seem to display as a preview on the first attempt. I seem to have to click upload again, it fails again, but if i click upload again and upload - it works on the third attempt. Maybe I am mistaken but I have tried on multiple browsers and seem to get the same result. (It freezes in safari on upload)
I believe the mistake is happening around fReader.onload
I am not concerned with uploading to a server - that is working. I am only looking to display the image as a preview on first attempted upload.
Cheers!

**Comment by jecfish** [comment]
fixed.
